version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /1_CRAM-to-BAM/CRAM-to-BAM.wdl
    testParameterFiles:
      - /1_CRAM-to-BAM/CRAM-to-BAM.json
    name: CRAM-to-BAM
    authors:
      - orcid: Broad Institute
  - subclass: WDL
    primaryDescriptorPath: /2_StripReadsFromBams/StripReadsFromBam.wdl
    testParameterFiles:
      - /2_StripReadsFromBams/StripReadsFromBam.json
    name: Strip-Reads-From-BAM
    authors:
      - orcid: 0000-0002-4243-5788
  - subclass: WDL
    primaryDescriptorPath: /3_read_alignment/t2t_alignment.wdl
    testParameterFiles:
        - /3_read_alignment/t2t_alignment.json
    name: T2T-alignment
    authors:
      - orcid: 0000-0001-5570-2059
      - orcid: 0000-0002-4243-5788
  - subclass: WDL
    primaryDescriptorPath: /4_haplotype_calling/haplotype_calling_chrom_female.wdl
    testParameterFiles:
        - /4_haplotype_calling/haplotype_calling_chrom_female.json
    name: haplotype-calling-chrom-female
    authors:
      - orcid: 0000-0001-5570-2059
      - orcid: 0000-0002-4243-5788
  - subclass: WDL
    primaryDescriptorPath: /5.1_Generate-Sample-Map/generate-sample-map.wdl
    testParameterFiles:
        - /5.1_Generate-Sample-Map/generate-sample-map.json
    name: generate-sample-map
    authors:
      - orcid: Broad Institute
  - subclass: WDL
    primaryDescriptorPath: /5.2_generateGenomicsDB/t2t_genomics_db.wdl
    testParameterFiles:
        - /5.2_generateGenomicsDB/t2t_genomics_db.json
    name: T2T-genomics-db
    authors:
      - orcid: 0000-0001-5570-2059
      - orcid: 0000-0002-4243-5788
  - subclass: WDL
    primaryDescriptorPath: /5.3_Joint_Genotyping/joint_genotyping.wdl
    testParameterFiles:
        - /5.3_Joint_Genotyping/joint_genotyping.json
    name: joint-genotyping
    authors:
      - orcid: 0000-0001-5570-2059
      - orcid: 0000-0002-4243-5788

  - subclass: WDL
    primaryDescriptorPath: /6-1.salmon/salmon.wdl
    testParameterFiles:
        - /6-1.salmon/salmon.json
    name: salmon
    authors:
      - orcid: 0000-0002-4243-5788
  - subclass: WDL
    primaryDescriptorPath: /6-1.salmon/process_quants.wdl
    testParameterFiles:
        - /6-1.salmon/process_quants.json
    name: process_quants
    authors:
      - orcid: 0000-0002-4243-5788
  - subclass: WDL
    primaryDescriptorPath: /6-1.salmon/collate_xy_quants.wdl
    testParameterFiles:
        - /6-1.salmon/collate_xy_quants.json
    name: collate_xy_quants
    authors:
      - orcid: 0000-0002-4243-5788
  - subclass: WDL
    primaryDescriptorPath: /6-1.salmon/collate_raw_quants.wdl
    testParameterFiles:
        - /6-1.salmon/collate_raw_quants.json
    name: collate_raw_quants
    authors:
      - orcid: 0000-0002-4243-5788
  - subclass: WDL
    primaryDescriptorPath: /6-1.salmon/collate_quant_diffs.wdl
    testParameterFiles:
        - /6-1.salmon/collate_quant_diffs.json
    name: collate_quant_diffs
    authors:
      - orcid: 0000-0002-4243-5788

  - subclass: WDL
    primaryDescriptorPath: /6-2.1_Hisat2_alignment/hisat2_alignment.wdl
    testParameterFiles:
        - /6-2.1_Hisat2_alignment/hisat2_alignment.json
    name: hisat2_alignment
    authors:
      - orcid: 0000-0002-4243-5788
      
  - subclass: WDL
    primaryDescriptorPath: /6-2.2_ASE/split_genotypes_for_ASE.wdl
    testParameterFiles:
        - /6-2.2_ASE/split_genotypes_for_ASE.json
    name: split_genotypes_for_ASE
    authors:
      - orcid: 0000-0002-4243-5788
  - subclass: WDL
    primaryDescriptorPath: /6-2.2_ASE/ASE.wdl
    testParameterFiles:
        - /6-2.2_ASE/ASE.json
    name: ASE
    authors:
      - orcid: 0000-0002-4243-5788
  - subclass: WDL
    primaryDescriptorPath: /6-2.2_ASE/process_ASE.wdl
    testParameterFiles:
        - /6-2.2_ASE/process_ASE.json
    name: process_ASE
    authors:
      - orcid: 0000-0002-4243-5788
  - subclass: WDL
    primaryDescriptorPath: /6-2.2_ASE/collate_ASE_stats.wdl
    testParameterFiles:
        - /6-2.2_ASE/collate_ASE_stats.json
    name: collate_ASE_stats
    authors:
      - orcid: 0000-0002-4243-5788

  - subclass: WDL
    primaryDescriptorPath: /misc/calc_stats.wdl
    testParameterFiles:
        - /misc/calc_stats.json
    name: calc_stats
    authors:
      - orcid: 0000-0002-4243-5788
  - subclass: WDL
    primaryDescriptorPath: /misc/tarchive.wdl
    testParameterFiles:
        - /misc/tarchive.json
    name: tarchive
    authors:
      - orcid: 0000-0002-4243-5788
